# Dominik Szot, 20.04.2023
# Laboratorium 06
# Kwadratury

# Zadanie 1

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.linalg as scp
import scipy.integrate as integrate

In [2]:
f_x = lambda x : 4./(1 + x**2)

In [8]:
def rectangular_method(nodes, values) -> None:
    accumulated = 0.

    for i in range(1, len(nodes)):
        accumulated += (nodes[i] - nodes[i-1])*values[i]
    
    return accumulated


In [12]:
m = 26

a = 0
b = 1

df2 = pd.DataFrame(data=[], index=None, columns=["K. Prostokątów", "K. Trapezów", "K. Simpsona"])

for i in range(1, m):
    no_nodes = 2**i + 1
    quadrature_nodes = np.array([a + i * (b-a)/(no_nodes-1) for i in range(no_nodes)])
    quadrature_points = [f_x(i) for i in quadrature_nodes]

    result_trapz = integrate.trapz(quadrature_points, quadrature_nodes, 1)
    result_simps = integrate.simps(quadrature_points, quadrature_nodes, 1)
    result_rectangle = rectangular_method(quadrature_nodes, quadrature_points);

    df2.loc[len(df2)] = [result_rectangle, result_trapz, result_simps]

df2 = df2.rename_axis('m', axis=1)
df2.index += 1
print(df2)

m   K. Prostokątów  K. Trapezów  K. Simpsona
1         2.600000     3.100000     3.133333
2         2.881176     3.131176     3.141569
3         3.013988     3.138988     3.141593
4         3.078442     3.140942     3.141593
5         3.110180     3.141430     3.141593
6         3.125927     3.141552     3.141593
7         3.133770     3.141582     3.141593
8         3.137684     3.141590     3.141593
9         3.139639     3.141592     3.141593
10        3.140616     3.141592     3.141593
11        3.141104     3.141593     3.141593
12        3.141349     3.141593     3.141593
13        3.141471     3.141593     3.141593
14        3.141532     3.141593     3.141593
15        3.141562     3.141593     3.141593
16        3.141577     3.141593     3.141593
17        3.141585     3.141593     3.141593
18        3.141589     3.141593     3.141593
19        3.141591     3.141593     3.141593
20        3.141592     3.141593     3.141593
21        3.141592     3.141593     3.141593
22        

In [40]:
errors = df2.to_numpy()
for i in range(len(errors)):
    for j in range(len(errors[i])):
        errors[i][j] = np.abs((np.pi - errors[i][j])/np.pi)

print(errors)


[[0.75854899 0.75854953 0.75854956]
 [0.75854929 0.75854956 0.75854957]
 [0.75854943 0.75854957 0.75854957]
 [0.7585495  0.75854957 0.75854957]
 [0.75854954 0.75854957 0.75854957]
 [0.75854955 0.75854957 0.75854957]
 [0.75854956 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [0.75854957 0.75854957 0.75854957]
 [1.11339852 1.11339852 6.63943727]]
